# Generated by Django 4.2.6 on 2024-06-27 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pivote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enunciado', models.CharField(max_length=500)),
                ('Tipo', models.CharField(max_length=100)),
                ('Respuesta', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.TextField()),
                ('Preguntas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pivote.preguntas')),
            ],
        ),
    ]
