# Generated by Django 4.2.6 on 2024-06-29 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pivote', '0002_preguntas_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(max_length=500)),
                ('tipo', models.CharField(choices=[('--', '-----'), ('De', 'Desarrollo'), ('SM', 'Seleccion Multiple')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Responde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_el', models.DateField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, null=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pivote.pregunta')),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='pivote.responde')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textOpcion', models.CharField(max_length=200)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiposPreguntas', to='pivote.pregunta')),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='Preguntas',
        ),
        migrations.RemoveField(
            model_name='test',
            name='Titulo',
        ),
        migrations.AddField(
            model_name='test',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Preguntas',
        ),
        migrations.AddField(
            model_name='respuesta',
            name='tipos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pivote.tipo'),
        ),
        migrations.AddField(
            model_name='responde',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pivote.test'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='pivote.test'),
        ),
        migrations.AddField(
            model_name='test',
            name='titulo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
