# Generated by Django 4.2 on 2024-06-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivote', '0002_preguntas_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preguntas',
            old_name='Enunciado',
            new_name='enunciado',
        ),
        migrations.RemoveField(
            model_name='preguntas',
            name='Respuesta',
        ),
        migrations.RemoveField(
            model_name='preguntas',
            name='Tipo',
        ),
        migrations.AddField(
            model_name='preguntas',
            name='opcionA',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='preguntas',
            name='opcionB',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='preguntas',
            name='opcionC',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='preguntas',
            name='opcionD',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
