# Generated by Django 4.2 on 2024-06-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivote', '0003_rename_enunciado_preguntas_enunciado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='preguntas',
            name='opcionA',
        ),
        migrations.RemoveField(
            model_name='preguntas',
            name='opcionB',
        ),
        migrations.RemoveField(
            model_name='preguntas',
            name='opcionC',
        ),
        migrations.RemoveField(
            model_name='preguntas',
            name='opcionD',
        ),
        migrations.AddField(
            model_name='preguntas',
            name='respuesta',
            field=models.ManyToManyField(to='pivote.opciones'),
        ),
    ]
