# Generated by Django 4.2 on 2024-06-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivote', '0004_opciones_remove_preguntas_opciona_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntas',
            name='respuesta',
        ),
        migrations.AddField(
            model_name='preguntas',
            name='opcionA',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='preguntas',
            name='opcionB',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='preguntas',
            name='opcionC',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='preguntas',
            name='opcionD',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Opciones',
        ),
    ]
